//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMA.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FMA.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo hinzufügen.
        /// </summary>
        public static string AddLogo {
            get {
                return ResourceManager.GetString("AddLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textfeld hinzufügen.
        /// </summary>
        public static string AddTextField {
            get {
                return ResourceManager.GetString("AddTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach unten ausrichten.
        /// </summary>
        public static string AlignBottom {
            get {
                return ResourceManager.GetString("AlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach links ausrichten.
        /// </summary>
        public static string AlignLeft {
            get {
                return ResourceManager.GetString("AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach rechts ausrichten.
        /// </summary>
        public static string AlignRight {
            get {
                return ResourceManager.GetString("AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach oben ausrichten.
        /// </summary>
        public static string AlignTop {
            get {
                return ResourceManager.GetString("AlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Dateien.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer erstellen.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material anlegen.
        /// </summary>
        public static string CreateMaterial {
            get {
                return ResourceManager.GetString("CreateMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Textfeld.
        /// </summary>
        public static string CustomFieldText {
            get {
                return ResourceManager.GetString("CustomFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo löschen.
        /// </summary>
        public static string DeleteLogo {
            get {
                return ResourceManager.GetString("DeleteLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selektierte Elemente löschen.
        /// </summary>
        public static string DeleteSelectedElements {
            get {
                return ResourceManager.GetString("DeleteSelectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textfeld löschen.
        /// </summary>
        public static string DeleteTextField {
            get {
                return ResourceManager.GetString("DeleteTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemente.
        /// </summary>
        public static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeres Material (*).
        /// </summary>
        public static string EmptyMaterial {
            get {
                return ResourceManager.GetString("EmptyMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor in einem zweiten Fenster öffnen.
        /// </summary>
        public static string ExternalEdit {
            get {
                return ResourceManager.GetString("ExternalEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorschau in einem zweiten Fenster öffnen.
        /// </summary>
        public static string ExternalPreview {
            get {
                return ResourceManager.GetString("ExternalPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feldname.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schriftfarbe.
        /// </summary>
        public static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schriftart.
        /// </summary>
        public static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schriftgröße.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schriftstil.
        /// </summary>
        public static string FontStyle {
            get {
                return ResourceManager.GetString("FontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild-Dateien.
        /// </summary>
        public static string ImageFiles {
            get {
                return ResourceManager.GetString("ImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Modus.
        /// </summary>
        public static string LayoutMode {
            get {
                return ResourceManager.GetString("LayoutMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Text darf maximal &apos;{0}&apos; Zeichen pro Zeile enthalten.
        /// </summary>
        public static string MaxLenghtHint {
            get {
                return ResourceManager.GetString("MaxLenghtHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Zeilenlänge.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Text darf maximal &apos;{0}&apos; Zeilen enthalten.
        /// </summary>
        public static string MaxLinesHint {
            get {
                return ResourceManager.GetString("MaxLinesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Anzahl Zeilen.
        /// </summary>
        public static string MaxRows {
            get {
                return ResourceManager.GetString("MaxRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position (Oben/Links).
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer auf Standard Werte zurücksetzen.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo-Datei auswählen.
        /// </summary>
        public static string SelectLogoFileTitle {
            get {
                return ResourceManager.GetString("SelectLogoFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückseite anzeigen.
        /// </summary>
        public static string ShowBackSide {
            get {
                return ResourceManager.GetString("ShowBackSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Größe (Breite/Höhe).
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farben in Form von WPF-Farben eingeben. z.B. &quot;Red&quot;,&quot;Pink&quot;,&quot;LightBlue&quot; oder als HexWert z.B. &quot;#FF0000&quot;.
        /// </summary>
        public static string TextColorToolTip {
            get {
                return ResourceManager.GetString("TextColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textfelder.
        /// </summary>
        public static string TextFields {
            get {
                return ResourceManager.GetString("TextFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansicht umschalten.
        /// </summary>
        public static string ToggleViews {
            get {
                return ResourceManager.GetString("ToggleViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versalschrift (Alles Großgeschrieben).
        /// </summary>
        public static string Versal {
            get {
                return ResourceManager.GetString("Versal", resourceCulture);
            }
        }
    }
}
