//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMA.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FMA.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Logo.
        /// </summary>
        public static string AddLogo {
            get {
                return ResourceManager.GetString("AddLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textfeld hinzufügen.
        /// </summary>
        public static string AddTextField {
            get {
                return ResourceManager.GetString("AddTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Bottom.
        /// </summary>
        public static string AlignBottom {
            get {
                return ResourceManager.GetString("AlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Left.
        /// </summary>
        public static string AlignLeft {
            get {
                return ResourceManager.GetString("AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Right.
        /// </summary>
        public static string AlignRight {
            get {
                return ResourceManager.GetString("AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Top.
        /// </summary>
        public static string AlignTop {
            get {
                return ResourceManager.GetString("AlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Textfeld.
        /// </summary>
        public static string CustomFieldText {
            get {
                return ResourceManager.GetString("CustomFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo löschen.
        /// </summary>
        public static string DeleteLogo {
            get {
                return ResourceManager.GetString("DeleteLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected elements.
        /// </summary>
        public static string DeleteSelectedElements {
            get {
                return ResourceManager.GetString("DeleteSelectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textfeld löschen.
        /// </summary>
        public static string DeleteTextField {
            get {
                return ResourceManager.GetString("DeleteTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemente.
        /// </summary>
        public static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Edit.
        /// </summary>
        public static string ExternalEdit {
            get {
                return ResourceManager.GetString("ExternalEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Preview.
        /// </summary>
        public static string ExternalPreview {
            get {
                return ResourceManager.GetString("ExternalPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldName.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontName.
        /// </summary>
        public static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontSize.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontStyle.
        /// </summary>
        public static string FontStyle {
            get {
                return ResourceManager.GetString("FontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Mode.
        /// </summary>
        public static string LayoutMode {
            get {
                return ResourceManager.GetString("LayoutMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position (Top/Left).
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückseite anzeigen.
        /// </summary>
        public static string ShowBackSide {
            get {
                return ResourceManager.GetString("ShowBackSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (Width/Height).
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textfelder.
        /// </summary>
        public static string TextFields {
            get {
                return ResourceManager.GetString("TextFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toogle Views.
        /// </summary>
        public static string ToggleViews {
            get {
                return ResourceManager.GetString("ToggleViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versalschrift (Alles Großgeschrieben).
        /// </summary>
        public static string Versal {
            get {
                return ResourceManager.GetString("Versal", resourceCulture);
            }
        }
    }
}
